# Generated by Django 4.0.4 on 2022-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('author_name', models.CharField(max_length=80)),
                ('pages', models.IntegerField()),
                ('price', models.CharField(max_length=80)),
            ],
        ),
    ]
