# Generated by Django 4.0.4 on 2022-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('publish_year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('price', models.CharField(max_length=80)),
            ],
        ),
    ]
